# Generated by Django 3.1.3 on 2020-11-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='date_watched',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='film',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='film',
            name='added',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='wishlisted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='FilmWatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Added')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
