# Generated by Django 3.1.3 on 2020-11-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_film_movie_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
