# Generated by Django 3.1.3 on 2020-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='critics_pick',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='director_of_photography',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='keyword_ids',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
