# Generated by Django 3.1.3 on 2020-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20201118_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cast',
            field=models.TextField(null=True),
        ),
    ]
