# Generated by Django 3.1.3 on 2020-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20201119_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
