# Generated by Django 3.1.3 on 2020-11-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre_ids',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
