# Generated by Django 3.1.3 on 2020-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_film_genre_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='assoc_producer_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='assoc_producers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='cast_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='director_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='director_of_photography_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='producer_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='review_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='screenplay',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='screenplay_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='story',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='story_ids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='director_of_photography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.TextField(null=True),
        ),
    ]
