# Generated by Django 3.1.3 on 2020-11-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20201119_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='assoc_producer_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='assoc_producers',
        ),
        migrations.RemoveField(
            model_name='film',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='film',
            name='cast_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director_of_photography',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director_of_photography_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='film',
            name='keyword_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producer_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='film',
            name='screenplay',
        ),
        migrations.RemoveField(
            model_name='film',
            name='screenplay_ids',
        ),
        migrations.RemoveField(
            model_name='film',
            name='story',
        ),
        migrations.RemoveField(
            model_name='film',
            name='story_ids',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('movie_db_id', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('movie_db_id', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
