# Generated by Django 3.1.3 on 2020-11-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20201125_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmCredit',
            new_name='ActingCredit',
        ),
        migrations.CreateModel(
            name='CrewCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('movie_db_id', models.IntegerField()),
                ('credit_id', models.CharField(max_length=200, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
