# Generated by Django 3.1.3 on 2020-11-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_auto_20201125_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewcredit',
            old_name='role',
            new_name='job',
        ),
    ]
