# Generated by Django 3.1.3 on 2020-12-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_auto_20201130_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='recommended',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
