# Generated by Django 3.1.3 on 2021-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
