# Generated by Django 3.1.3 on 2021-01-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_token_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expiry',
            field=models.IntegerField(default=0),
        ),
    ]
