# Generated by Django 3.1.3 on 2021-01-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
