# Generated by Django 3.1.3 on 2020-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='known_for',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
