# Generated by Django 3.1.3 on 2020-12-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_actingcredit_crewcredit_genre_keyword_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='title',
            new_name='name',
        ),
    ]
