# Generated by Django 3.1.3 on 2020-12-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_first_air_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='genres',
        ),
    ]
