# Generated by Django 3.1.3 on 2020-12-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_remove_show_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actingcredit',
            old_name='role',
            new_name='character',
        ),
        migrations.AddField(
            model_name='crewcredit',
            name='known_for',
            field=models.CharField(default='Production', max_length=200, null=True),
        ),
    ]
